CREATE TABLE `zs_popup` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '弹窗id',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '弹窗标题',
  `is_open` tinyint(4) NOT NULL DEFAULT '0' COMMENT '状态 1开启 0关闭',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '弹窗类型 0版本更新 1认证 2活动 3购物卡',
  `show_type` tinyint(1) DEFAULT '0' COMMENT '弹窗位置 0 中间 1底部 2浮动',
  `remind_ver` varchar(20) NOT NULL DEFAULT '' COMMENT '提醒版本阈值',
  `is_forced` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否强制更新 1是 0否',
  `remind_content` text NOT NULL COMMENT '提醒文案内容',
  `remind_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '提醒模式 1时间周期 0永久提醒',
  `certif_range` tinyint(4) NOT NULL DEFAULT '0' COMMENT '认证范围 1注册时间 0全部用户',
  `certif_regtime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '认证注册时间',
  `bg_img` text COMMENT '背景图片',
  `jump_way` tinyint(4) NOT NULL DEFAULT '0' COMMENT '跳转方式 1H5-URL 0原生',
  `url_h5` text COMMENT 'H5-URL',
  `android_url` text COMMENT '安卓路径page',
  `ios_url` text COMMENT 'IOS路径page',
  `user_type` varchar(10) NOT NULL DEFAULT '0' COMMENT '弹窗人群 0全部用户 1非钻用户 2钻石用户 3新用户 4老用户',
  `frequency` tinyint(4) NOT NULL DEFAULT '0' COMMENT '提醒频次 0仅提醒一次 1每次启动 2每天启动 3间隔时长',
  `frequency_interval` tinyint(4) NOT NULL DEFAULT '0' COMMENT '提醒频次间隔时长(小时)',
  `show_time` tinyint(4) NOT NULL DEFAULT '3' COMMENT '浮动弹窗展示时长(3秒~30秒)',
  `start_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '开启时间',
  `end_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '结束时间',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加时间',
  `updated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `index` (`id`,`type`,`show_type`)
) ENGINE=InnoDB AUTO_INCREMENT=72 DEFAULT CHARSET=utf8 COMMENT='弹窗表';

